### ISSUE TITLE
Additional internal link checks

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#15]
https://github.com/byuitechops/action-series-master/blob/5dfc264eb4d23f952f4608fb17a40485a6ad8512/actions/universal-target-attributes.js#L19-L34

Can we add it so it doesn't touch links that don't have the domain in them? Sometimes anchor tags will just have an element ID or a URI instead, like this: 

```html
<a href="#someID">Potato</a>

<a href="/some/place/on/current/site">tomato</a>

**Comment by sethchilders92** [comment]
@zlw11063 is line 20 as seen above not doing that? If that isn't what you are talking about, I can talk to you in person about it.

**Comment by zlw11063** [comment]
@sethchilders92 Oh, I see. I think I meant links that don't have a domain at all in them. i.e. `www.byui.instructure.com/some/place/on/current/site` vs. `/some/place/on/current/site`.

**Comment by sethchilders92** [comment]
Done.

**Comment by sethchilders92** [comment]
Removed eachChar and used string indexing instead.
