### ISSUE TITLE
Add external links from module-items set-external-links

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#18]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-set-external-links.js#L15-L19

We can add the links from `set-external-links` in module items. They should go to the same links, I would think.

**Comment by sethchilders92** [comment]
@zlw11063 Ready for review in universal-set-external-links branch
