### ISSUE TITLE
"typeof alt !== undefined" to just "undefined"

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#20]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-remove-banners.js#L33

You can change this to just ```js
alt !== '' && alt !== undefined```

Then it won't have to run `typeof`.

**Comment by csammcgrath** [comment]
This is now resolved through the latest pull request.
