### ISSUE TITLE
Change course.log() to item.techops.log()

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#21]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-remove-banners.js#L44-L46

Change this to use `item.techops.log`. It has the same syntax, but waits to log the change until *after* the PUT request happens when the item finishes running through all of the grandchildren.

**Comment by csammcgrath** [comment]
This is now resolved through the latest pull request.
