### ISSUE TITLE
Switch to regex.text()

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#23]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-remove-banners.js#L10

Using `regex.match()` returns an array of all matches in the text. Give `regex.test()` a shot instead. It just returns true or false, which is what the if statement needs.

**Comment by csammcgrath** [comment]
Should be fixed with the latest pull request.
