### ISSUE TITLE
Remove `beginProcessCallback` parameter

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#24]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L26

`beginProcessCallback` is never passed to `beginProcess()` or used in it. Looks like you changed it to just use the final `callback` provided in the `module.exports` parameters.

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
