### ISSUE TITLE
ES6 Goodness

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#25]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L323-L325

You can change this to:
```js
var dropbox = course.content.find(file => file.name === 'dropbox_d2l.xml');
```

Isn't ES6 beautiful?

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
