### ISSUE TITLE
Change IF to just check if it is undefined, rather than typeof

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#26]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L328

You can change this to just ```js
dropbox !== 'undefined'
```

Make sure to use the `!==` rather than `!=`.

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
