### ISSUE TITLE
Switch to Warning

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#33]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L259-L263

You'd know better than me, but would this be better as a warning instead of an error? If a dropbox can't be found, it might be because it was removed. For example, dropboxes with [CO~] in them are removed by another grandchild. Since it might be intentionally gone, it would be good to just put a warning in instead.

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
