### ISSUE TITLE
ES6 Goodness Round 2

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#34]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L234-L242

This can be switched to ES6 magic:

```js
function getCanvasUrl(link) {
    //find the Canvas assignment that we are looking for.
    return canvasAssignments.find(canvasAssignment => canvasAssignment.name === link.d2l.name);
}
```

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
