### ISSUE TITLE
Potential scoping issue

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/action-series-master#37]
https://github.com/byuitechops/action-series-master/blob/6242a2ffc0f996c03860c1fecf92d3674e47ac5e/actions/universal-fix-dropbox-links.js#L295-L306

You may want to change the "item" parameter to a different name, since the `module.exports` function brings in an "item" as well. Since the highlighted code above is in the scope of the `module.exports` function, this could cause scoping issues.

**Comment by csammcgrath** [comment]
Fixed with the latest pull request.
